version: "3.8"
services:
  firstapi:
    build: ./first
    container_name: first_container
    ports:
      - "4000:4000"
    volumes: 
      - ./first:/app
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_container
    ports:
      - "3000:3000"
    # volumes: 
    #   - ./myblog:/app
    #   - /app/node_modules
    stdin_open: true
    tty: true
